namespace BotCarniceria.Core.Domain.Enums;

public enum ConversationState
{
    START,
    MENU,
    ASK_NAME,
    ASK_ADDRESS,
    TAKING_ORDER,
    SELECT_PAYMENT,
    AWAITING_CONFIRM,
    CONFIRM_ADDRESS,
    CONFIRM_LATE_ORDER,
    ADDING_MORE,
    BILLING_WARNING,
    BILLING_CHECK_DATA,
    BILLING_ASK_RAZON_SOCIAL,
    BILLING_ASK_RFC,
    BILLING_ASK_CALLE,
    BILLING_ASK_NUMERO,
    BILLING_ASK_COLONIA,
    BILLING_ASK_CP,
    BILLING_ASK_CORREO,
    BILLING_ASK_REGIMEN,
    BILLING_CONFIRM_DATA,
    BILLING_ASK_NOTE_FOLIO,
    BILLING_ASK_NOTE_TOTAL,
    BILLING_ASK_CFDI
}
